name: Build CSS

on: [ workflow_dispatch ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
      - name: Build CSS with lessc
        run: npx -p less lessc public/less/index.less public/css/index.css
      - name: Commit and push update
        run: |
          git config --global user.name "gogs-custom[bot]"
          git config --global user.email "russell_aunger@wycliffeassociates.org"
          git add public/css/index.css
          git commit -m "Build index.css from index.less" && git push
