name: Build CSS

on:
  push:
    branches-ignore:
      # Don't run on continuous-deployment branches
      content*.bibletranslationtools.org

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
      - name: Build CSS with lessc
        run: npx -p less lessc public/less/index.less public/css/index.css
      - name: Minify CSS
        run: |
          npx -p clean-css-cli cleancss public/css/index.css -o public/css/index-min.css
          mv public/css/index-min.css public/css/index.css
      - name: Commit and push update
        run: |
          git config --global user.name "gogs-custom[bot]"
          git config --global user.email "russell_aunger@wycliffeassociates.org"
          git add public/css/index.css
          git commit -m "Build index.css from index.less"
          if [ $? -eq 0 ]
          then git push
          fi
